#options(timeout = max(1000, getOption("timeout")))
#install.packages("sf")
#install.packages("devtools")
#install.packages('gridExtra')
#install.packages("alphahull")
#install.packages(c("randomForest", "gstat", "readxl"))
#install.packages("SpatialML")
#devtools::install_github("imbs-hl/ranger")
#install.packages("ncdf4")
#install.packages("fields")
#install.packages("rgdal")
#install.packages("pdp")
#install.packages("terra")
#library("devtools")
#devtools::install_github("cran/GSIF")
#install.packages("doParallel")
#install.packages("CAST")
#install.packages("geosphere")
#install.packages("graph4lg")
#install.packages("dsm")
#xinstall.packages("sdmpredictors")
#install.packages("leaflet")

library("sdmpredictors")
library("leaflet")
library("dsm")
library("dplyr")
library("graph4lg")
library("geosphere")
library("CAST")
#library("doParallel")
#library("GSIF")
library("SpatialML")
library("sf")
library("dplyr")
library("ncdf4")
library("fields")
library("raster")
require(rgdal)
library("zoo")
library("caret")
library("randomForest")
require("purrr")
library("pdp")
library("readxl")
library("rgeos")
library("alphahull")
library("gstat")
library("caret")
#install.packages("raster")
library("raster")
library("terra")


#install.packages(
#  "ggOceanMapsData", 
#  repos = c("https://mikkovihtakari.github.io/drat", 
#            "https://cloud.r-project.org")
#)

library("ggOceanMaps")
